name: Build

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read 
  packages: read

jobs:
  build:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build
