name: Release

on:
  release:
    types: [published]  

permissions:
  contents: write
  packages: write

jobs:
  version:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    outputs:
      version: ${{ steps.get-tag-version.outputs.version }}

    steps:
      - name: Get Tag Version
        id: get-tag-version
        shell: bash
        run: |
          tagName="${{ github.event.release.tag_name }}"
          version="${tagName#v}"  # Removes the 'v' prefix if it exists
          echo "Extracted version $version from tag"
          echo "version=$version" >> "$GITHUB_OUTPUT"

  publish:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    needs: [version]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install distutils
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils python3.11 python3.11-distutils python3-pip

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install twine setuptools wheel pytest

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with setup.py using version
        run: |
          export PACKAGE_VERSION=${{ needs.version.outputs.version }}
          python setup.py sdist bdist_wheel

      - name: Publish to QChem on Pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*