name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest
