name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install distutils
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils python3.11 python3.11-distutils python3-pip

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install twine setuptools wheel pytest

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  test:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    needs: [setup]
    steps:
      - name: Run tests
        run: pytest
